package com.immortalwrt.manager.domain.model

enum class RouterConnectionState {
    UNKNOWN, CHECKING, ONLINE, OFFLINE,
    AUTH_REQUIRED, AUTH_FAILED, PERMISSION_DENIED,
    CERTIFICATE_UNTRUSTED, CERTIFICATE_CHANGED,
    ENDPOINT_UNAVAILABLE, UNSUPPORTED_FIRMWARE
}
